#!/bin/bash
mon(2)				eniac man page				       	man(2)

NAME 
     eniac- the first electronic general-purpose digital computer.

SYNOPSIS 
	 eniac

DESCRIPTION
	Eniac was Turing-complete, and able to solve "a large class of numerical problems" through reprogramming.

OPTIONS 
	eniac does not take any options.

SEE ALSO
    ENIAC could be programmed to perform complex sequences of operation(2), including loop(2), and subtoutines(2).

BUGS 
     No known bugs.

AUTHOR
	University of Pennsylvania.
0.32					10 December 1945			man(2)